### PR TITLE
Update the tests to new API

### PR DESCRIPTION
**Pull request by timholy**
This copies the old tests to `tests/deprecations.jl` and updates `runtests.jl` to use the new API. The main tests pass even with `julia --depwarn=error` (though it will error when it `include`s the `test/deprecations.jl` file).

### CODE REVIEW

**Comment by timholy** [comment]
Once this gets merged to `master`, then I'd recommend the following steps:

- you can release version 0.1.1 simply by commenting `@JuliaRegistrator register` on the most recent commit on the `master` branch, https://github.com/rdoelman/ZernikePolynomials.jl/commits/master/ (it should be the commit that merges this PR)
- once 0.1.1 is available, your users have a smooth path to upgrading to the new API, with helpful warnings telling them how to update their code. From that point, whenever you wish you can adopt a "clean" version of the package by making the new API required:
  + delete `src/deprecations.jl` and `test/deprecations.jl`
  + remove the corresponding `include("deprecations.jl")` directives in `src/ZernickePolynomials.jl` and `test/runtests.jl`
  + bump the version in `Project.toml` to `0.2.0`
  + release

 Bumping the version to 0.2.0 signals a breaking change, which is important because by removing the deprecations you make the old API not work anymore.

**Comment by timholy** [comment]
Bump. It would be nice to get a release with these changes. If you're unsure of how to do such things, I personally would recommend transferring this package to JuliaMath (see #4) so that others can take on the maintenance burden for this package.

**Comment by timholy** [comment]
Bump

**Comment by timholy** [comment]
@rdoelman, would you like help with the items in https://github.com/rdoelman/ZernikePolynomials.jl/pull/7#issuecomment-2058845091? If you [invite me to collaborate](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository) on this repo I can take those steps.

**Comment by rdoelman** [comment]
That would be very much appreciated! I've added you.

**Comment by timholy** [comment]
Thanks! Looks like there may be one step you'll have to take: can you click the "Install app" button on https://github.com/JuliaRegistries/Registrator.jl?tab=readme-ov-file#via-the-web-interface. You'll likely have to choose whether you want to install it on all your repositories or just a select subset. I've chosen it for all of mine:
image

When that's done, I think I'll have permissions for the rest, so let me know when it's ready.

**Comment by timholy** [comment]
@rdoelman, there's nothing I can do until you add the Registrator app (<60s of work). If you do that I can handle the rest.

Alternatively, #4 remains an option if you'd prefer. At JuliaMath I could do the whole thing. It's just a permission issue.

**Comment by rdoelman** [comment]
I've taken care of it.

**Comment by timholy** [comment]
It works! https://github.com/JuliaRegistries/General/pull/115980

**Pull request merged**
